apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: homepage
data:
  settings.yaml: |
    headerStyle: boxedWidgets
    useEqualHeights: true
    showStats: true
    layout:
      Hardware:
        tab: Hardware
        style: row
        columns: 2
      Admin:
        tab: Admin
        style: row
        columns: 2
      Media:
        tab: Media
        style: row
        columns: 2
      Asterisk:
        tab: Asterisk
        style: row
        columns: 2

  bookmarks.yaml: |
    - Work:
        - Github:
            - icon: github-light
              href: https://github.com/Tuckerbradburn
        - Webmail:
            - abbr: MAIL
              href: https://www.office365.us/
    - Shopping:
        - Amazon:
            - icon: amazon
              href: https://www.amazon.com/
        - Newegg:
            - icon: newegg
              href: https://www.newegg.com/
        - Ebay:
            - icon: ebay
              href: https://www.ebay.com/
    - Entertainment:
        - YouTube:
            - icon: youtube
              href: https://youtube.com/

  services.yaml: ""
  widgets.yaml: ""
  kubernetes.yaml: |
    mode: cluster
  docker.yaml: ""
  custom.css: ""
  custom.js: ""
